version: '2.1'

volumes:
  redis-volume: {}
  mongo-volume: {}

services:
  api:
    build:
      context: .
      dockerfile: docker-node
    volumes:
      - /usr/app/api/node_modules
      - ./app:/usr/app/api/app
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - NODE_ENV=${NODE_ENV} # It should be needed to pass NODE_ENV from shell to node

  redis:
    image: redis:4.0.8
    volumes:
      - redis-volume:/data
    ports:
      - '6379'
    command: redis-server --appendonly yes

  mongo:
    image: mongo:3.6.3
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017'
